# Generated by Django 2.1.7 on 2019-07-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='gubun',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
