# Generated by Django 2.1.7 on 2019-07-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_board_gubun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='content',
        ),
        migrations.RemoveField(
            model_name='board',
            name='gubun',
        ),
        migrations.RemoveField(
            model_name='board',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='title',
        ),
    ]
