# Generated by Django 2.1.7 on 2019-07-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190709_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='gubun',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='reg_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
