# Generated by Django 2.1.7 on 2019-07-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='SettingsInfo',
        ),
    ]
