# Generated by Django 2.1.7 on 2019-07-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190711_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsinfo',
            old_name='reg_pass',
            new_name='itemval',
        ),
        migrations.AddField(
            model_name='settingsinfo',
            name='itemkey',
            field=models.CharField(default='key', max_length=30),
            preserve_default=False,
        ),
    ]
